services:
    dfgs:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                # only for local!
                NEXT_PUBLIC_API_URL: "http://127.0.0.1:7002"
        container_name: dfgs
        ports:
            - "7001:3000"
    dfgs-api:
        image: dta32/ofgs-api:latest
        container_name: dfgs-api
        ports:
            - "7002:3000"
        environment:
            DATABASE_URL: "mongoUrl"
            SERVER_PORT: "port"
            API_PREFIX: "/anythingorcanbeemptytoo"
