services:
    dfgs:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        container_name: dfgs
        restart: unless-stopped
        ports:
            - "7001:3000"
    dfgs-api:
        image: dfgs-api:latest
        container_name: dfgs-api
        restart: unless-stopped
        ports:
            - "7002:3000"
